name: ackr-portfolio
services:
- name: web
  source_dir: /
  github:
    repo: AustinCKR/MyPage
    branch: main
    deploy_on_push: true
  build_command: dotnet publish -c Release -o ./publish
  run_command: cd ./publish && dotnet MyPage.dll
  environment_slug: dotnet
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    value: Production
  - key: ASPNETCORE_URLS
    value: http://0.0.0.0:8080